-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 18:16:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dowload_posts_reddit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dowload_posts_reddit` ;

-- -----------------------------------------------------
-- Schema dowload_posts_reddit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dowload_posts_reddit` DEFAULT CHARACTER SET utf8 ;
USE `dowload_posts_reddit` ;

-- -----------------------------------------------------
-- Table `dowload_posts_reddit`.`reddit_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dowload_posts_reddit`.`reddit_post` ;

CREATE TABLE IF NOT EXISTS `dowload_posts_reddit`.`reddit_post` (
  `idreddit_post` INT NOT NULL AUTO_INCREMENT,
  `subreddit` VARCHAR(100) NOT NULL,
  `post_url` VARCHAR(250) NULL,
  `created` TIMESTAMP NULL,
  `name` VARCHAR(10) NULL,
  `subreddit_id` VARCHAR(100) NULL,
  `post_id` VARCHAR(100) NULL,
  PRIMARY KEY (`idreddit_post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dowload_posts_reddit`.`imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dowload_posts_reddit`.`imagem` ;

CREATE TABLE IF NOT EXISTS `dowload_posts_reddit`.`imagem` (
  `idimagem` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `hashsum` VARCHAR(200) NULL,
  `width` INT NULL,
  `height` INT NULL,
  PRIMARY KEY (`idimagem`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dowload_posts_reddit`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dowload_posts_reddit`.`tag` ;

CREATE TABLE IF NOT EXISTS `dowload_posts_reddit`.`tag` (
  `idtag` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idtag`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dowload_posts_reddit`.`imagem_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dowload_posts_reddit`.`imagem_tag` ;

CREATE TABLE IF NOT EXISTS `dowload_posts_reddit`.`imagem_tag` (
  `idimagem` INT NOT NULL,
  `idtag` INT NOT NULL,
  PRIMARY KEY (`idimagem`, `idtag`),
  INDEX `fk_imagem_has_tag_tag1_idx` (`idtag` ASC) VISIBLE,
  INDEX `fk_imagem_has_tag_imagem_idx` (`idimagem` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_has_tag_imagem`
    FOREIGN KEY (`idimagem`)
    REFERENCES `dowload_posts_reddit`.`imagem` (`idimagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagem_has_tag_tag1`
    FOREIGN KEY (`idtag`)
    REFERENCES `dowload_posts_reddit`.`tag` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dowload_posts_reddit`.`variante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dowload_posts_reddit`.`variante` ;

CREATE TABLE IF NOT EXISTS `dowload_posts_reddit`.`variante` (
  `idimagem` INT NOT NULL,
  `idvariante` INT NOT NULL,
  PRIMARY KEY (`idimagem`, `idvariante`),
  INDEX `fk_imagem_has_imagem_imagem2_idx` (`idvariante` ASC) VISIBLE,
  INDEX `fk_imagem_has_imagem_imagem1_idx` (`idimagem` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_has_imagem_imagem1`
    FOREIGN KEY (`idimagem`)
    REFERENCES `dowload_posts_reddit`.`imagem` (`idimagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagem_has_imagem_imagem2`
    FOREIGN KEY (`idvariante`)
    REFERENCES `dowload_posts_reddit`.`imagem` (`idimagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dowload_posts_reddit`.`reddit_imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dowload_posts_reddit`.`reddit_imagem` ;

CREATE TABLE IF NOT EXISTS `dowload_posts_reddit`.`reddit_imagem` (
  `idimagem` INT NOT NULL,
  `idreddit_post` INT NOT NULL,
  `media_id` VARCHAR(100) NULL,
  PRIMARY KEY (`idimagem`, `idreddit_post`),
  INDEX `fk_reddit_imagem_has_imagem_imagem1_idx` (`idimagem` ASC) VISIBLE,
  INDEX `fk_reddit_url_post_reddit1_idx` (`idreddit_post` ASC) VISIBLE,
  CONSTRAINT `fk_reddit_imagem_has_imagem_imagem1`
    FOREIGN KEY (`idimagem`)
    REFERENCES `dowload_posts_reddit`.`imagem` (`idimagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reddit_url_post_reddit1`
    FOREIGN KEY (`idreddit_post`)
    REFERENCES `dowload_posts_reddit`.`reddit_post` (`idreddit_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
